<a href="https://colab.research.google.com/github/kaushal-codes/Data-Science/blob/main/Assignment_1_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# **Table of Contents**
---

**1.** [**Introduction to Numpy**](#Section1)<br>
**2.** [**Installing & Importing Libraries**](#Section2)<br>
  - **2.1** [**Installing Libraries**](#Section21)
  - **2.2** [**Importing Libraries**](#Section22)

**3.** [**Speed Check**](#Section3)<br>
**4.** [**Creating Numpy Arrays**](#Section4)<br>
**5.** [**Checking the Array Attributes**](#Section5)<br>
**6.** [**Conclusion**](#Section6)<br>


---
<a name = Section1></a>
# **1. Introduction to Numpy**
---

- **Numpy** is a library developed for Python which can handle large, multi-dimensional arrays and matrices. 

- It has a large **collections of mathematical functions** to operate on these arrays.

- It is **remarkably faster** than Python Lists for many reasons.

- It was designed for __efficient data storage__. All the elements of numpy arrays are stored __sequentially__ with a fixed width for each value. 

- On the other hand Lists are pointers to data stored elsewhere. The number of separate reads the computer has to do is smaller for numpy.

- Numpy has __uniform datatypes__ instead of Lists. The computer performs a logic for each different element type. 

- Due to this reason numpy completely avoids the extra computation.

- Numpy has __optimized functions__ for many mathematical operations on arrays and matrices. 

- This is the reason they are faster than regular math operations on lists.


---
<a name = Section2></a>
# **2. Installing & Importing Libraries**
---

- To refer to the official documentation of Numpy click <a href="https://numpy.org/doc/stable/">**here**</a>.

<a name = Section21></a>
### **2.1 Installing Libraries**

In [1]:
!pip install -q --upgrade numpy

     |████████████████████████████████| 15.7 MB 5.1 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.3.post1 requires numpy<1.20,>=1.16.0, but you have numpy 1.21.4 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


<a name = Section22></a>
### **2.2 Importing Libraries**

- We can give an alias name of np, so that we dont have to repeatedly use the longer form of the name.

In [2]:
import numpy as np                                                  # Importing package numpys (For Numerical Python)
import time                                                         # Importing time package

---
<a name = Section3></a>
# **3. Speed Check**
---

- In this section, we will perform speed comparison between Python Lists and Numpy.

In [3]:
size_of_vec = 1000000

def pure_python_version():                                                # This function will return the time for python calculation
    time_python = time.time()                                             # Start time before operation
    my_list1 = range(size_of_vec)                                         # Creating a list with 1000000 values
    my_list2 = range(size_of_vec)
    sum_list = [my_list1[i] + my_list2[i] for i in range(len(my_list1))]  # Calculating the sum
    return time.time() - time_python                                      # Return Current time - start time

def numpy_version():                                                      # This function will return the time for numpy calculation
    time_numpy = time.time()                                              # Start time before operation
    my_arr1 = np.arange(size_of_vec)                                      # Creating a numpy array of 1000000 values
    my_arr2 = np.arange(size_of_vec)
    sum_array = my_arr1 + my_arr2                                         # Calculate the sum
    return time.time() - time_numpy                                       # Return current time - start time


python_time = pure_python_version()                                       # Time taken for Python expression
numpy_time = numpy_version()                                              # Time taken for numpy operation
print("Pure Python version {:0.4f}".format(python_time))
print("Numpy version {:0.4f}".format(numpy_time))
print("Numpy is in this example {:0.4f} times faster!".format(python_time/numpy_time))

Pure Python version 0.3325
Numpy version 0.0075
Numpy is in this example 44.1186 times faster!


**Observations:**

- We observed that Numpy is way more faster than Python list.

- Also its more convenient when handling large datasets at once.

---
<a name = Section4></a>
# **4. Creating Numpy Arrays**
---

- The key feature of numpy is its N-dimensional array or ndarray, having the below specialities:

- It is **fast** and **flexible** container for large datasets in Python.

- These arrays **enable** you to carry **mathematical operations** on whole block of data.

- It is a **generic multi-dimensional container** for data, where each element is of the same type. 

- Below we will see some examples of ndarray showing 1D, 2D and 3D arrays:

<center><img src=""></center>

In [4]:
# Creating python list
my_list = [1, 2, 3, 4, 5]

# Dispaly the type of my_list variable
print('Type:', type(my_list))

# Output python list values
my_list

Type: <class 'list'>


[1, 2, 3, 4, 5]

In [5]:
# Creating 1-dimensional array using python list declared earlier
arr = np.array(my_list)

# Dispaly the type of arr variable
print('Type:', type(arr))

# Output array values
arr

Type: <class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [6]:
[1,2]
[[1,2],[3,4]]
[[[0.5,0.5],[0.5,0.5,0.5,0.5]],[[0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5],[0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]]]

[[[0.5, 0.5], [0.5, 0.5, 0.5, 0.5]],
 [[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]]]

In [7]:
# Creating a python list containing sub-lists of values
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

# Creating 2-dimensional array using python list of my_mat
mat = np.array(my_mat) 

# Dispaly the type of mat variable
print('Type:', type(mat))

# Output array values
mat

Type: <class 'numpy.ndarray'>


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Observation:**

- Numpy arrays have the same functionalities as Python lists but the difference lies in their functionality and speed of doing operations.

- The important diference in working with Numpy arrays is its more __convenient and fast__.

- ndarrays are widely used for __handling images__ as huge matrices of numbers.

- And its easier and faster to do any image operations in numpy arrays as compared to Python lists.

---
<a name = Section5></a>
# **5. Checking the Array Attributes**
---

- You might be interested to know the shape, dimensionality and datatype of the elements in the ndarray.

- Here are some numpy functions to know these attributes:
  - **.shape:** It gives the information about the dimensions of an ndarray.

  - **.ndim:** It gives the information about the resolution of an ndarray.

  - **.dtype:** It gives the information about the type or layout of data being stored by ndarray.

In [8]:
# Dispaly the type of arr variable
print('Type:', type(arr))

# Output array values
arr

Type: <class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [9]:
# Creating a python list containing sub-lists of values
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

# Creating 2-dimensional array using python list of my_mat
mat = np.array(my_mat) 

# Output array values
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
# Display the array and matrix shape
print('Array Shape:', arr.shape)
print('Matrix Shape:', mat.shape)

Array Shape: (5,)
Matrix Shape: (4, 3)


In [11]:
# Display the resolution of an array and matrix
print('Array Resolution:', arr.ndim)
print('Matrix Resolution:', mat.ndim)

Array Resolution: 1
Matrix Resolution: 2


In [12]:
# Display the type of the ndarray
print('Type of information stored in an array:', arr.dtype)
print('Type of information stored in a matrix :', mat.dtype)

Type of information stored in an array: int64
Type of information stored in a matrix : int64


**Observation:**

- We have seen how easy it is to make use of shape, ndim and dtype function to check the shape, dimension and datatype of the array.

---
<a name = Section6></a>
# **6. Conclusion**
---

- **Numpy** is an **open-source** add-on module to Python.

- By using Numpy you can **speed up** your **workflow** operations.

- You can **interface** with **other packages** in the Python ecosystem that use Numpy under the hood.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays.

- It provides common mathematical and numerical routines in pre-compiled, fast functions.

- It **provides basic routines** for manipulating large arrays and matrices of numeric data.

- NumPy arrays have a fixed size decided at the time of creation. 

- Changing the size of an array will create a new array and delete the original.

- The **elements** in a NumPy array are all **required** to be of the **same data type**, and thus will be the same size in memory.

- NumPy arrays **facilitate advanced mathematical** and other types of **operations** on large numbers of data.